<a href="https://colab.research.google.com/github/DannyData1419/CM3710-ML-AI/blob/main/CAR_EVALUATION_WITH_KERAS_NN_V1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CAR EVALUATION WITH KERAS NN V1

In [1]:
import pandas as pd

# Import data
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data'
column_names = ['buying', 'maintenance', 'doors', 'persons', 'lug_boot', 'safety', 'class']

df = pd.read_csv(url, names=column_names, skipinitialspace=True)

import numpy as np

# One-hot-encode features
buying = pd.get_dummies(df['buying'])
maintenance = pd.get_dummies(df['maintenance'])
doors = pd.get_dummies(df['doors'])
persons = pd.get_dummies(df['persons'])
lug_boot = pd.get_dummies(df['lug_boot'])
safety = pd.get_dummies(df['safety'])

# Concat one-hot-encoded features to df
df = pd.concat((buying, maintenance, doors, persons, lug_boot, safety, df), axis=1)

# Drop original features from df 
df = df.drop(['buying', 'maintenance', 'doors', 'persons', 'lug_boot', 'safety'], axis=1)

# Create target and features
X = df.drop('class', axis=1).values
y = df['class'].values

print(X)

[[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 1 0 0]
 ...
 [0 1 0 ... 0 1 0]
 [0 1 0 ... 0 0 1]
 [0 1 0 ... 1 0 0]]


In [2]:
# One-hot target for keras NN
y = pd.get_dummies(y)
print(y)

      acc  good  unacc  vgood
0       0     0      1      0
1       0     0      1      0
2       0     0      1      0
3       0     0      1      0
4       0     0      1      0
...   ...   ...    ...    ...
1723    0     1      0      0
1724    0     0      0      1
1725    0     0      1      0
1726    0     1      0      0
1727    0     0      0      1

[1728 rows x 4 columns]


In [3]:
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Create train + test split of data 80/20 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=8, stratify=y)

# Model 1
model1 = keras.Sequential(
    [
        keras.Input(shape=(X_train.shape[1])), # Input layer=4
        layers.Dense(64, activation='relu'),
        layers.Dense(64, activation='sigmoid'),
        layers.Dense(4, activation='softmax') # Output layer=4
     ]
)

# Model 2
model2 = keras.Sequential(
    [
        keras.Input(shape=(X_train.shape[1])), # Input layer=4
        layers.Dense(64, activation='relu'),
        layers.Dense(64, activation='sigmoid'),
        layers.Dense(4, activation='softmax') # Output layer=4
     ]
)

# View model summary
model1.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                1408      
                                                                 
 dense_1 (Dense)             (None, 64)                4160      
                                                                 
 dense_2 (Dense)             (None, 4)                 260       
                                                                 
Total params: 5,828
Trainable params: 5,828
Non-trainable params: 0
_________________________________________________________________


In [4]:
# Compile the model
from keras import metrics
# metrics=['accuracy', 'Precision', 'Recall', 'AUC', 'MeanSquaredError']

# Model 1 using loss='binary_crossentropy', optimizer='adam' 
model1.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy', 'Precision', 'Recall', 'AUC', 'MeanSquaredError'])

# Model 2 using loss='categorical_crossentropy', optimizer='sgd'
model2.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy', 'Precision', 'Recall', 'AUC', 'MeanSquaredError'])

epochs = 10 # epochs = number of training iterations examining the full training set
batch_size = 16 # keep batch size low for small datasets 

# Train model
model1.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, validation_data=(X_test, y_test))

model2.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, validation_data=(X_test, y_test))

Epoch 1/10
87/87 [==============================] - 7s 24ms/step - loss: 0.4137 - accuracy: 0.6657 - precision: 0.7007 - recall: 0.6013 - auc: 0.8590 - mean_squared_error: 0.1244 - val_loss: 0.3369 - val_accuracy: 0.6994 - val_precision: 0.6994 - val_recall: 0.6994 - val_auc: 0.9297 - val_mean_squared_error: 0.1154
Epoch 2/10
87/87 [==============================] - 2s 18ms/step - loss: 0.2883 - accuracy: 0.7178 - precision: 0.7307 - recall: 0.7106 - auc: 0.9438 - mean_squared_error: 0.0884 - val_loss: 0.2441 - val_accuracy: 0.7572 - val_precision: 0.7846 - val_recall: 0.7370 - val_auc: 0.9609 - val_mean_squared_error: 0.0698
Epoch 3/10
87/87 [==============================] - 1s 12ms/step - loss: 0.2030 - accuracy: 0.8430 - precision: 0.8589 - recall: 0.8278 - auc: 0.9741 - mean_squared_error: 0.0558 - val_loss: 0.1921 - val_accuracy: 0.8092 - val_precision: 0.8136 - val_recall: 0.7948 - val_auc: 0.9715 - val_mean_squared_error: 0.0637
Epoch 4/10
87/87 [==============================]

In [5]:
# Train model
model2.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, validation_data=(X_test, y_test))

Epoch 1/10
87/87 [==============================] - 0s 4ms/step - loss: 0.7747 - accuracy: 0.7004 - precision: 0.7004 - recall: 0.7004 - auc: 0.9225 - mean_squared_error: 0.1045 - val_loss: 0.7811 - val_accuracy: 0.6994 - val_precision: 0.6994 - val_recall: 0.6994 - val_auc: 0.9241 - val_mean_squared_error: 0.1051
Epoch 2/10
87/87 [==============================] - 0s 3ms/step - loss: 0.7634 - accuracy: 0.7004 - precision: 0.7004 - recall: 0.7004 - auc: 0.9276 - mean_squared_error: 0.1024 - val_loss: 0.7721 - val_accuracy: 0.6994 - val_precision: 0.6994 - val_recall: 0.6994 - val_auc: 0.9270 - val_mean_squared_error: 0.1049
Epoch 3/10
87/87 [==============================] - 0s 3ms/step - loss: 0.7528 - accuracy: 0.7004 - precision: 0.7004 - recall: 0.7004 - auc: 0.9287 - mean_squared_error: 0.1012 - val_loss: 0.7569 - val_accuracy: 0.6994 - val_precision: 0.6994 - val_recall: 0.6994 - val_auc: 0.9293 - val_mean_squared_error: 0.1012
Epoch 4/10
87/87 [==============================] - 

In [6]:
# Test model1 on validation data
score = model1.evaluate(X_test, y_test,verbose=0)
print('Evaluation metrics:\nloss:', score[0], '\naccuracy:',score[1], '\nprecision:',score[2], '\nrecall:', score[3], '\nAUC:', score[4], '\nMSE:', score[5])


Evaluation metrics:
loss: 0.10334122180938721 
accuracy: 0.9161849617958069 
precision: 0.9294478297233582 
recall: 0.8757225275039673 
AUC: 0.9932785630226135 
MSE: 0.028487715870141983


In [7]:
# Test model2 on validation data
score = model2.evaluate(X_test, y_test,verbose=0)
print('Evaluation metrics:\nloss:', score[0], '\naccuracy:',score[1], '\nprecision:',score[2], '\nrecall:', score[3], '\nAUC:', score[4], '\nMSE:', score[5])

Evaluation metrics:
loss: 0.6370258927345276 
accuracy: 0.7196531891822815 
precision: 0.7908496856689453 
recall: 0.6994219422340393 
AUC: 0.9402544498443604 
MSE: 0.08295272290706635
