<a href="https://colab.research.google.com/github/DannyData1419/CM3710-ML-AI/blob/main/CAR_EVALUATION_WITH_NEURAL_NETWORK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Import data
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data'
column_names = ['buying', 'maintenance', 'doors', 'persons', 'lug_boot', 'safety', 'class']

raw_dataset = pd.read_csv(url, names=column_names, skipinitialspace=True)
df = raw_dataset

# View sample of raw dataset
#df.sample(10)

In [ ]:
# Preprocess nominal features into numbers
import numpy as np

# One-hot-encode features
buying = pd.get_dummies(df['buying'])
maintenance = pd.get_dummies(df['maintenance'])
doors = pd.get_dummies(df['doors'])
persons = pd.get_dummies(df['persons'])
lug_boot = pd.get_dummies(df['lug_boot'])
safety = pd.get_dummies(df['safety'])

# Concat one-hot-encoded features to df
df = pd.concat((buying, maintenance, doors, persons, lug_boot, safety, df), axis=1)

# Drop original features from df 
df = df.drop(['buying', 'maintenance', 'doors', 'persons', 'lug_boot', 'safety'], axis=1)

# Create target and features
X = df.drop('class', axis=1).values
y = df['class'].values

print(f"Preprocessed one-hot shape: {df.shape} \n{X}")

Preprocessed one-hot shape: (1728, 22) 
[[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 1 0 0]
 ...
 [0 1 0 ... 0 1 0]
 [0 1 0 ... 0 0 1]
 [0 1 0 ... 1 0 0]]


In [ ]:
# One-hot target for keras
y = pd.get_dummies(y)
print(y)

      acc  good  unacc  vgood
0       0     0      1      0
1       0     0      1      0
2       0     0      1      0
3       0     0      1      0
4       0     0      1      0
...   ...   ...    ...    ...
1723    0     1      0      0
1724    0     0      0      1
1725    0     0      1      0
1726    0     1      0      0
1727    0     0      0      1

[1728 rows x 4 columns]


In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Create train + test split of data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=8, stratify=y)

model = Sequential()
model.add(Dense(32, input_shape=(X_train.shape[1],), activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(4, activation='sigmoid'))

# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model on the data
history = model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/10
44/44 [==============================] - 1s 8ms/step - loss: 0.6280 - accuracy: 0.5832 - val_loss: 0.5302 - val_accuracy: 0.6994
Epoch 2/10
44/44 [==============================] - 0s 3ms/step - loss: 0.4487 - accuracy: 0.7004 - val_loss: 0.3800 - val_accuracy: 0.6994
Epoch 3/10
44/44 [==============================] - 0s 3ms/step - loss: 0.3386 - accuracy: 0.7004 - val_loss: 0.3104 - val_accuracy: 0.6994
Epoch 4/10
44/44 [==============================] - 0s 3ms/step - loss: 0.2798 - accuracy: 0.7127 - val_loss: 0.2603 - val_accuracy: 0.7225
Epoch 5/10
44/44 [==============================] - 0s 3ms/step - loss: 0.2306 - accuracy: 0.7562 - val_loss: 0.2172 - val_accuracy: 0.7717
Epoch 6/10
44/44 [==============================] - 0s 3ms/step - loss: 0.1906 - accuracy: 0.8278 - val_loss: 0.1878 - val_accuracy: 0.8092
Epoch 7/10
44/44 [==============================] - 0s 3ms/step - loss: 0.1647 - accuracy: 0.8502 - val_loss: 0.1686 - val_accuracy: 0.8410
Epoch 8/10
44/44 [==

In [ ]:
# Model evaluation
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=2)
print('Test accuracy:', test_acc)

11/11 - 0s - loss: 0.1362 - accuracy: 0.8671 - 38ms/epoch - 3ms/step
Test accuracy: 0.8670520186424255
