<a href="https://colab.research.google.com/github/DannyData1419/CM3710-ML-AI/blob/main/CAR_EVALUATION_WITH_KERAS_NN_V0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CAR EVALUATION WITH KERAS NN V0

In [1]:
import pandas as pd

# Import data
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data'
column_names = ['buying', 'maintenance', 'doors', 'persons', 'lug_boot', 'safety', 'class']

df = pd.read_csv(url, names=column_names, skipinitialspace=True)

# Preprocess nominal features into numbers
import numpy as np

# One-hot-encode features
buying = pd.get_dummies(df['buying'])
maintenance = pd.get_dummies(df['maintenance'])
doors = pd.get_dummies(df['doors'])
persons = pd.get_dummies(df['persons'])
lug_boot = pd.get_dummies(df['lug_boot'])
safety = pd.get_dummies(df['safety'])

# Concat one-hot-encoded features to df
df = pd.concat((buying, maintenance, doors, persons, lug_boot, safety, df), axis=1)

# Drop original features from df 
df = df.drop(['buying', 'maintenance', 'doors', 'persons', 'lug_boot', 'safety'], axis=1)

# Create target and features
X = df.drop('class', axis=1).values
y = df['class'].values

print(X)

[[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 1 0 0]
 ...
 [0 1 0 ... 0 1 0]
 [0 1 0 ... 0 0 1]
 [0 1 0 ... 1 0 0]]


In [2]:
# One-hot target for keras NN
y = pd.get_dummies(y)
print(y)

      acc  good  unacc  vgood
0       0     0      1      0
1       0     0      1      0
2       0     0      1      0
3       0     0      1      0
4       0     0      1      0
...   ...   ...    ...    ...
1723    0     1      0      0
1724    0     0      0      1
1725    0     0      1      0
1726    0     1      0      0
1727    0     0      0      1

[1728 rows x 4 columns]


In [3]:
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Create train + test split of data 80/20 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=8, stratify=y)

model1 = Sequential()
model1.add(Dense(32, input_shape=(X_train.shape[1],), activation='relu'))
model1.add(Dense(16, activation='relu'))
model1.add(Dense(4, activation='sigmoid'))

# View model summary
model1.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                704       
                                                                 
 dense_1 (Dense)             (None, 16)                528       
                                                                 
 dense_2 (Dense)             (None, 4)                 68        
                                                                 
Total params: 1,300
Trainable params: 1,300
Non-trainable params: 0
_________________________________________________________________


In [4]:
# Compile the model
from keras import metrics

# Model 1 using loss='binary_crossentropy', optimizer='adam' 
model1.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

epochs = 10 # epochs = number of training iterations examining the full training set
batch_size = 16 # keep batch size low for small datasets 

# Train model
model1.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, validation_data=(X_test, y_test))

Epoch 1/10
87/87 [==============================] - 2s 6ms/step - loss: 0.5356 - accuracy: 0.5507 - val_loss: 0.3649 - val_accuracy: 0.6994
Epoch 2/10
87/87 [==============================] - 1s 8ms/step - loss: 0.3059 - accuracy: 0.7019 - val_loss: 0.2574 - val_accuracy: 0.7341
Epoch 3/10
87/87 [==============================] - 1s 8ms/step - loss: 0.2124 - accuracy: 0.8126 - val_loss: 0.1917 - val_accuracy: 0.8382
Epoch 4/10
87/87 [==============================] - 1s 11ms/step - loss: 0.1620 - accuracy: 0.8726 - val_loss: 0.1611 - val_accuracy: 0.8555
Epoch 5/10
87/87 [==============================] - 1s 11ms/step - loss: 0.1379 - accuracy: 0.8799 - val_loss: 0.1438 - val_accuracy: 0.8642
Epoch 6/10
87/87 [==============================] - 1s 10ms/step - loss: 0.1239 - accuracy: 0.8864 - val_loss: 0.1324 - val_accuracy: 0.8728
Epoch 7/10
87/87 [==============================] - 1s 6ms/step - loss: 0.1139 - accuracy: 0.9067 - val_loss: 0.1223 - val_accuracy: 0.9017
Epoch 8/10
87/87 

In [5]:
# Test model1 on validation data
score = model1.evaluate(X_test, y_test,verbose=2)
print('Evaluation metrics:\nloss:', score[0], '\naccuracy:',score[1])

11/11 - 0s - loss: 0.0999 - accuracy: 0.9191 - 88ms/epoch - 8ms/step
Evaluation metrics:
loss: 0.09993091225624084 
accuracy: 0.9190751314163208
