<a href="https://colab.research.google.com/github/DannyData1419/CM3710-ML-AI/blob/main/CAR_EVALUATION_WITH_NEURAL_NETWORK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# Import data
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data'
column_names = ['buying', 'maintenance', 'doors', 'persons', 'lug_boot', 'safety', 'class']

raw_dataset = pd.read_csv(url, names=column_names, skipinitialspace=True)
df = raw_dataset

# View sample of raw dataset
df.sample(10)

buying maintenance  doors persons lug_boot safety  class
570    high        high      3       2      med    low  unacc
315   vhigh         med  5more    more    small    low  unacc
1593    low         med  5more       2    small    low  unacc
1722    low         low  5more    more      med    low  unacc
78    vhigh       vhigh      4    more      big    low  unacc
184   vhigh        high      4    more      med    med  unacc
627    high        high  5more       2      big    low  unacc
1053    med        high  5more       2    small    low  unacc
923     med       vhigh      4       2      med   high  unacc
740    high         med  5more       4    small   high    acc

In [2]:
# Preprocess nominal features into numbers
import numpy as np

# One-hot-encode features
buying = pd.get_dummies(df['buying'])
maintenance = pd.get_dummies(df['maintenance'])
doors = pd.get_dummies(df['doors'])
persons = pd.get_dummies(df['persons'])
lug_boot = pd.get_dummies(df['lug_boot'])
safety = pd.get_dummies(df['safety'])

# Concat one-hot-encoded features to df
df = pd.concat((buying, maintenance, doors, persons, lug_boot, safety, df), axis=1)

# Drop original features from df 
df = df.drop(['buying', 'maintenance', 'doors', 'persons', 'lug_boot', 'safety'], axis=1)

# Create target and features
X = df.drop('class', axis=1).values
y = df['class'].values

print(f"Feature: {X.shape} \n{X}")

Feature: (1728, 21) 
[[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 1 0 0]
 ...
 [0 1 0 ... 0 1 0]
 [0 1 0 ... 0 0 1]
 [0 1 0 ... 1 0 0]]


In [3]:
# One-hot target for keras NN
y = pd.get_dummies(y)
print(y)

      acc  good  unacc  vgood
0       0     0      1      0
1       0     0      1      0
2       0     0      1      0
3       0     0      1      0
4       0     0      1      0
...   ...   ...    ...    ...
1723    0     1      0      0
1724    0     0      0      1
1725    0     0      1      0
1726    0     1      0      0
1727    0     0      0      1

[1728 rows x 4 columns]


In [4]:
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Create train + test split of data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=8, stratify=y)

model = Sequential()
model.add(Dense(32, input_shape=(X_train.shape[1],), activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(4, activation='sigmoid'))

# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model on the data
history = model.fit(X_train, y_train, epochs=100, batch_size=16, validation_data=(X_test, y_test))

Epoch 1/100
87/87 [==============================] - 1s 5ms/step - loss: 0.5605 - accuracy: 0.6100 - val_loss: 0.3987 - val_accuracy: 0.6994
Epoch 2/100
87/87 [==============================] - 0s 3ms/step - loss: 0.3159 - accuracy: 0.7171 - val_loss: 0.2701 - val_accuracy: 0.7168
Epoch 3/100
87/87 [==============================] - 0s 3ms/step - loss: 0.2273 - accuracy: 0.8068 - val_loss: 0.2104 - val_accuracy: 0.8266
Epoch 4/100
87/87 [==============================] - 0s 3ms/step - loss: 0.1805 - accuracy: 0.8603 - val_loss: 0.1808 - val_accuracy: 0.8555
Epoch 5/100
87/87 [==============================] - 0s 3ms/step - loss: 0.1544 - accuracy: 0.8792 - val_loss: 0.1604 - val_accuracy: 0.8584
Epoch 6/100
87/87 [==============================] - 0s 3ms/step - loss: 0.1360 - accuracy: 0.8799 - val_loss: 0.1451 - val_accuracy: 0.8584
Epoch 7/100
87/87 [==============================] - 0s 3ms/step - loss: 0.1227 - accuracy: 0.8922 - val_loss: 0.1329 - val_accuracy: 0.8671
Epoch 8/100
8

In [5]:
# Model evaluation
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=2)
print('Test accuracy:', test_acc)

11/11 - 0s - loss: 0.0172 - accuracy: 0.9884 - 38ms/epoch - 3ms/step
Test accuracy: 0.9884393215179443


A Keras Sequential neural network (NN) is a type of feedforward neural network that consists of a sequence of layers. Each layer in the network takes the output of the previous layer as input and performs a set of operations on it to produce a new output. The layers in the network can be of different types such as dense, convolutional, or recurrent, each serving a specific purpose in the model architecture.

During training, the network is optimized using an optimizer such as stochastic gradient descent (SGD) to minimize a loss function, which measures the difference between the predicted outputs and the actual outputs. The network is trained by adjusting the weights of the connections between the layers until the loss is minimized.

Once the model is trained, it can be used to make predictions on new input data by passing it through the network and obtaining the output from the final layer. Keras Sequential NNs are easy to build and train, making them a popular choice for a wide range of machine learning tasks such as image classification, natural language processing, and time series forecasting.