<a href="https://colab.research.google.com/github/DannyData1419/CM3710-ML-AI/blob/main/CAR_EVALUATION_WITH_NEURAL_NETWORK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# Import data
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data'
column_names = ['buying', 'maintenance', 'doors', 'persons', 'lug_boot', 'safety', 'class']

raw_dataset = pd.read_csv(url, names=column_names, skipinitialspace=True)
df = raw_dataset

# View sample of raw dataset
df.sample(10)

buying maintenance  doors persons lug_boot safety  class
1520    low         med      2       2      big   high  unacc
966     med       vhigh  5more    more      med    low  unacc
432    high       vhigh      2       2    small    low  unacc
1495    low        high  5more       4    small    med    acc
963     med       vhigh  5more    more    small    low  unacc
185   vhigh        high      4    more      med   high  unacc
1493    low        high  5more       2      big   high  unacc
959     med       vhigh  5more       4      med   high    acc
1155    med         med      4    more      med    low  unacc
706    high         med      4       2      med    med  unacc

In [2]:
# Preprocess nominal features into numbers
import numpy as np

# One-hot-encode features
buying = pd.get_dummies(df['buying'])
maintenance = pd.get_dummies(df['maintenance'])
doors = pd.get_dummies(df['doors'])
persons = pd.get_dummies(df['persons'])
lug_boot = pd.get_dummies(df['lug_boot'])
safety = pd.get_dummies(df['safety'])

# Concat one-hot-encoded features to df
df = pd.concat((buying, maintenance, doors, persons, lug_boot, safety, df), axis=1)

# Drop original features from df 
df = df.drop(['buying', 'maintenance', 'doors', 'persons', 'lug_boot', 'safety'], axis=1)

# Create target and features
X = df.drop('class', axis=1).values
y = df['class'].values

print(f"Preprocessed one-hot shape: {df.shape} \n{X}")

Preprocessed one-hot shape: (1728, 22) 
[[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 1 0 0]
 ...
 [0 1 0 ... 0 1 0]
 [0 1 0 ... 0 0 1]
 [0 1 0 ... 1 0 0]]


In [3]:
# One-hot target for keras
y = pd.get_dummies(y)
print(y)

      acc  good  unacc  vgood
0       0     0      1      0
1       0     0      1      0
2       0     0      1      0
3       0     0      1      0
4       0     0      1      0
...   ...   ...    ...    ...
1723    0     1      0      0
1724    0     0      0      1
1725    0     0      1      0
1726    0     1      0      0
1727    0     0      0      1

[1728 rows x 4 columns]


In [4]:
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Create train + test split of data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=8, stratify=y)

model = Sequential()
model.add(Dense(32, input_shape=(X_train.shape[1],), activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(4, activation='sigmoid'))

# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model on the data
history = model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/10
44/44 [==============================] - 9s 70ms/step - loss: 0.5352 - accuracy: 0.4971 - val_loss: 0.4279 - val_accuracy: 0.6994
Epoch 2/10
44/44 [==============================] - 1s 28ms/step - loss: 0.3685 - accuracy: 0.7012 - val_loss: 0.3371 - val_accuracy: 0.6994
Epoch 3/10
44/44 [==============================] - 1s 23ms/step - loss: 0.3102 - accuracy: 0.7004 - val_loss: 0.2979 - val_accuracy: 0.7081
Epoch 4/10
44/44 [==============================] - 1s 26ms/step - loss: 0.2712 - accuracy: 0.7315 - val_loss: 0.2611 - val_accuracy: 0.7225
Epoch 5/10
44/44 [==============================] - 1s 24ms/step - loss: 0.2333 - accuracy: 0.7706 - val_loss: 0.2262 - val_accuracy: 0.7688
Epoch 6/10
44/44 [==============================] - 1s 18ms/step - loss: 0.1992 - accuracy: 0.8249 - val_loss: 0.1971 - val_accuracy: 0.8208
Epoch 7/10
44/44 [==============================] - 1s 16ms/step - loss: 0.1733 - accuracy: 0.8430 - val_loss: 0.1767 - val_accuracy: 0.8497
Epoch 8/10
44

In [5]:
# Model evaluation
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=2)
print('Test accuracy:', test_acc)

11/11 - 0s - loss: 0.1455 - accuracy: 0.8613 - 106ms/epoch - 10ms/step
Test accuracy: 0.8612716794013977
